[package]
name = "board"
version = "0.0.0-unreleased"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.1"
cortex-m-rt = "0.6.10"
delog = "0.1.0-alpha.3"
fm11nc08 = {path = "../../../components/fm11nc08"}
nb = "1"
trussed = { path = "../../../components/trussed", features = ["clients-3"] }

[dependencies.lpc55-hal]
git = "https://github.com/lpc55/lpc55-hal"
branch = "main"
features = ["littlefs", "rtic-peripherals"]
# path = "../../../../lpc55-hal"

[features]
board-solov2 = []
board-lpcxpresso55 = []

[patch.crates-io]
heapless = { git = "https://github.com/nickray/heapless", branch = "bytebuf-0.5.6" }
nisty = {git = "https://github.com/ycrypto/nisty", branch="main"}

[profile.release]
codegen-units = 1
# lto = true
# opt-level = "s"
incremental = false
debug = true
