[package]
name = "provisioner-app"
version = "0.1.0"
authors.workspace = true
edition = "2024"

[dependencies]
apdu-dispatch .workspace = true
defmt         .workspace = true
heapless      .workspace = true
iso7816       .workspace = true
lpc55-hal     .workspace = true
littlefs2     .workspace = true
trussed       .workspace = true
p256  = { version = "0.9", default-features = false, features = ["arithmetic"] }
salty         .workspace = true

[features]
test-attestation = []
