[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip LPC55S69JBD100"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-Dwarnings",
]

[build]
target = "thumbv8m.main-none-eabi"
