[package]
name = "ndef-app"
version = "0.1.0"
authors.workspace = true
edition = "2024"

[dependencies]
heapless       .workspace = true
apdu-dispatch  .workspace = true
cortex-m       .workspace = true
iso7816        .workspace = true
littlefs2      .workspace = true
trussed-core   = { workspace = true, features = ["filesystem-client"] }
