[package]
name = "app"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[lib]
name = "app"

[[bin]]
name = "pc"
path = "src/app_pc.rs"

[dependencies]
chacha20 = { version = "0.6.0", features = ["rng"] }
heapless = "0.5.5"
nb = "1"
embedded-hal = { version = "0.2", features = ["unproven"] }
generic-array = "0.14.3"

# components
c-stubs = { path = "../../components/c-stubs" }
trussed = { path = "../../components/trussed", features = ["clients-3"] }
ctap-types = { path = "../../components/ctap-types" }
fido-authenticator = { path = "../../components/fido-authenticator" }
interchange = { path = "../../components/interchange" }
piv-card = { path = "../../components/piv-card" }
usbd-ccid = { path = "../../components/usbd-ccid" }
usbd-ctaphid = { path = "../../components/usbd-ctaphid" }
iso14443 = {path = "./../../components/iso14443"}
apdu-dispatch = {path = "./../../components/apdu-dispatch", features=["std"]}
hid-dispatch = {path = "./../../components/hid-dispatch"}
applet-ndef = {path = "./../../components/applet-ndef"}
applet-root = {path = "./../../components/applet-root"}
applet-fido = {path = "./../../components/applet-fido"}
delog = "0.1.0-alpha.3"

# storage
# littlefs2 = { git = "https://github.com/nickray/littlefs2", branch = "main" }
littlefs2 = { git = "https://github.com/nickray/littlefs2", branch = "closures-instead-of-ub" }

[features]
default = []

# Use to auto-succeed every user presence check
no-buttons= []


reconfig = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

# patch dependencies like so to test local changes

[patch.crates-io]
heapless = { git = "https://github.com/nickray/heapless", branch = "bytebuf-0.5.6" }
nisty = {git = "https://github.com/ycrypto/nisty", branch="main"}

[profile.release]
codegen-units = 1
opt-level = "z"
incremental = false
debug = true
