// SPDX-License-Identifier: MIT
//
//! Chip-layer driver — FFI to Nordic's MIT-licensed `nrfx_nfct.c`,
//! pre-compiled into `vendor/lib/libnrfx_nfct.a`.
//!
//! The bindgen output is committed at `vendor/nrfx_nfct_bindings.rs`;
//! this module just `include!`s it and adds two C-ABI helpers the
//! driver needs at runtime (critical-section + microsecond delay).
//!
//! IRQ handlers `nrfx_nfct_irq_handler` and
//! `nrfx_nfct_workaround_timer_handler` are exported by the .a; the
//! runner's RTIC `binds = NFCT` / `binds = TIMER4` tasks call them.

// Pre-generated by bindgen — see vendor/README.md and the regen target.
include!("../vendor/nrfx_nfct_bindings.rs");

// ── Critical section ─────────────────────────────────────────────────────
//
// nrfx's critical-section convention: enter() returns a state that exit()
// restores. We mirror PRIMASK behavior so nested critical sections nest
// correctly: enter() saves the current PRIMASK and disables interrupts;
// exit() writes the saved value back.
//
// We avoid `cortex_m::interrupt::free` because that closure-based API
// doesn't compose with the C macro pattern (enter/exit on different lines).

#[unsafe(no_mangle)]
pub extern "C" fn nrfx_critical_section_enter() -> u8 {
    let primask = cortex_m::register::primask::read();
    cortex_m::interrupt::disable();
    if primask.is_active() {
        0
    } else {
        1
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn nrfx_critical_section_exit(saved: u8) {
    if saved == 0 {
        // PRIMASK was clear (interrupts enabled) before enter() — re-enable.
        unsafe { cortex_m::interrupt::enable() };
    }
}

// ── Microsecond delay (busy loop, calibrated for 64 MHz core) ────────────

#[unsafe(no_mangle)]
pub extern "C" fn nrfx_delay_us(us: u32) {
    // cortex_m::asm::delay takes cycles; at 64 MHz, 64 cycles = 1 µs.
    cortex_m::asm::delay(us.saturating_mul(64));
}
