# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check-dev"

[jobs]

[jobs.check-dev]
command = ["cargo", "check", "--color", "always", "--features", "board-lpcxpresso55,develop"]
need_stdout = false

[jobs.build-dev]
command = ["cargo", "build", "--color", "always", "--release", "--features", "board-lpcxpresso55,develop"]
need_stdout = false

[jobs.check]
command = ["cargo", "check", "--color", "always", "--features"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--tests", "--color", "always"]
need_stdout = false

[jobs.light]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true

