[package]
name = "app"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[lib]
name = "app"

[[bin]]
name = "rtic"
path = "src/app_rtic.rs"

[dependencies]
cortex-m-rtic = "0.5.1"
cortex-m-semihosting = "0.3.5"
delog = "0.1.0-alpha.3"
heapless = "0.5.5"
nb = "1"
usb-device = "0.2.3"
usbd-serial = "0.1.0"

# board
lpc55-hal = { git = "https://github.com/lpc55/lpc55-hal", branch = "main" }
lpcxpresso55 = { path = "../../boards/lpcxpresso55", optional = true }
prototype-bee = { path = "../../boards/prototype-bee", optional = true }
board-traits = { path = "../../boards/board-traits" }

# components
c-stubs = { path = "../../components/c-stubs" }
trussed = { path = "../../components/trussed", features = ["clients-3"] }
ctap-types = { path = "../../components/ctap-types" }
fido-authenticator = { path = "../../components/fido-authenticator" }
interchange = { path = "../../components/interchange" }
piv-card = { path = "../../components/piv-card" }
usbd-ccid = { path = "../../components/usbd-ccid" }
usbd-ctaphid = { path = "../../components/usbd-ctaphid" }
fm11nc08 = {path = "../../components/fm11nc08"}
iso14443 = {path = "../../components/iso14443"}
apdu-dispatch = {path = "../../components/apdu-dispatch"}
hid-dispatch = {path = "../../components/hid-dispatch"}
applet-ndef = {path = "../../components/applet-ndef"}
applet-root = {path = "../../components/applet-root"}
applet-fido = {path = "../../components/applet-fido"}

# panic
panic-halt = "0.2.0"
panic-semihosting = { version = "0.5.3", features = ["jlink-quirks"] }

# storage
# littlefs2 = { git = "https://github.com/nickray/littlefs2", branch = "main" }
littlefs2 = { git = "https://github.com/nickray/littlefs2", branch = "closures-instead-of-ub" }

[features]
default = []

# Do not use encryption for the filesystem
no-encrypted-storage = []

# Use to auto-succeed every user presence check
no-buttons= []

board-lpcxpresso = ["lpcxpresso55"]
board-prototype = ["prototype-bee"]

log-serial = []

highspeed = []
serial = []
reconfig = []
no-clock-controller = []
enable-clock-controller-signal-pin = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

# patch dependencies like so to test local changes

[patch.crates-io]
heapless = { git = "https://github.com/nickray/heapless", branch = "bytebuf-0.5.6" }
nisty = {git = "https://github.com/ycrypto/nisty", branch="main"}

# micro-ecc-sys = { path = "../../../micro-ecc-sys" }
# littlefs2-sys = { path = "../../../littlefs2-sys" }

# [patch."https://github.com/lpc55/lpc55-hal"]
# lpc55-hal = {git = "https://github.com/nickray/lpc55-hal", branch = "rand-core" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
incremental = false
debug = true

# Speed up crypto packages
[profile.release.package.salty]
opt-level = 2

[profile.release.package.nisty]
opt-level = 2
