[package]
name = "board"
version = "0.0.0-unreleased"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[dependencies]
delog = "0.1.0"
fm11nc08 = {path = "../../../components/fm11nc08"}
lpc55-hal = { version = "0.3", features = ["littlefs", "rtic-peripherals"] }
nb = "1"
trussed = { git = "https://github.com/trussed-dev/trussed" }

[features]
board-lpcxpresso55 = []
board-okdoe1 = ["board-lpcxpresso55"]
board-solo2 = []

no-buttons = []
no-clock-controller = []
enable-clock-controller-signal-pin = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[profile.release]
codegen-units = 1
# lto = true
# opt-level = "s"
incremental = false
debug = true

