[package]
name = "board"
version = "0.1.0-unreleased"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2021"

[dependencies]
admin-app = "0.1"
delog = "0.1"
fm11nc08 = {path = "../../../components/fm11nc08"}
lpc55-hal = { version = "0.3", features = ["littlefs", "rtic-peripherals"] }
lpc55-rtic = "0.5.7"
micromath = "2"
nb = "1"
trussed = "0.1"

[features]
lpcxpresso55 = []
okdoe1 = ["lpcxpresso55"]
solo2 = []

no-buttons = []
no-clock-controller = []
enable-clock-controller-signal-pin = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[profile.release]
codegen-units = 1
# lto = true
# opt-level = "s"
incremental = false
debug = true

