[package]
name = "iso14443"
version = "0.0.1"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[dependencies]
cortex-m-funnel = { git = "https://github.com/conorpp/cortex-m-funnel" }
cortex-m = "0.6.1"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.5"
nb = "0.1"
ufmt = "0.1.0"

apdu-manager = {path = "../apdu-manager"}
iso7816 = {path = "../iso7816"}
logging = {path = "../logging"}
fm11nc08 = {path = "../fm11nc08"}